; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=aarch64-linux-gnu < %s | FileCheck -check-prefix=GNU %s

; fp128 exp10 lowers to exp10l where long double is fp128, and diagnoses a
; missing libcall (instead of crashing) where it is not.

; RUN: not llc -mtriple=aarch64-apple-macosx -filetype=null %s 2>&1 | FileCheck -check-prefix=ERR %s
; RUN: not llc -mtriple=aarch64-windows-msvc -filetype=null %s 2>&1 | FileCheck -check-prefix=ERR %s
; RUN: not llc -mtriple=aarch64-linux-android -filetype=null %s 2>&1 | FileCheck -check-prefix=ERR %s

; ERR: error: no libcall available for fexp10

define fp128 @test_exp10_f128(fp128 %x) {
; GNU-LABEL: test_exp10_f128:
; GNU:       // %bb.0:
; GNU-NEXT:    b exp10l
  %r = call fp128 @llvm.exp10.f128(fp128 %x)
  ret fp128 %r
}
