; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=aarch64-linux-gnu < %s | FileCheck -check-prefix=GNU %s

; fp128 frexp lowers to frexpl where long double is fp128, and
; diagnoses a missing libcall when it is not.

; RUN: not llc -mtriple=aarch64-apple-macosx -filetype=null %s 2>&1 | FileCheck -check-prefix=ERR %s
; RUN: not llc -mtriple=aarch64-windows-msvc -filetype=null %s 2>&1 | FileCheck -check-prefix=ERR %s
; RUN: not llc -mtriple=aarch64-linux-android -filetype=null %s 2>&1 | FileCheck -check-prefix=ERR %s

; ERR: error: no libcall available for ffrexp

define { fp128, i32 } @test_frexp_f128_i32(fp128 %a) nounwind {
; GNU-LABEL: test_frexp_f128_i32:
; GNU:       // %bb.0:
; GNU-NEXT:    str x30, [sp, #-16]! // 8-byte Folded Spill
; GNU-NEXT:    add x0, sp, #12
; GNU-NEXT:    bl frexpl
; GNU-NEXT:    ldr w0, [sp, #12]
; GNU-NEXT:    ldr x30, [sp], #16 // 8-byte Folded Reload
; GNU-NEXT:    ret
  %call = call { fp128, i32 } @llvm.frexp.f128.i32(fp128 %a)
  ret { fp128, i32 } %call
}
