; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=aarch64-linux-gnu < %s | FileCheck -check-prefix=GNU %s

; fp128 ldexp lowers to ldexpl where long double is fp128, and
; diagnoses a missing libcall where it is not.

; RUN: not llc -mtriple=aarch64-apple-macosx -filetype=null %s 2>&1 | FileCheck -check-prefix=ERR %s
; RUN: not llc -mtriple=aarch64-windows-msvc -filetype=null %s 2>&1 | FileCheck -check-prefix=ERR %s
; RUN: not llc -mtriple=aarch64-linux-android -filetype=null %s 2>&1 | FileCheck -check-prefix=ERR %s

; ERR: error: no libcall available for fldexp

define fp128 @test_ldexp_f128_i32(fp128 %val, i32 %a) {
; GNU-LABEL: test_ldexp_f128_i32:
; GNU:       // %bb.0:
; GNU-NEXT:    b ldexpl
  %call = tail call fp128 @llvm.ldexp.f128.i32(fp128 %val, i32 %a)
  ret fp128 %call
}
